npm_config_disturl="https://npmmirror.com/dist"
npm_config_sharp_binary_host="https://npmmirror.com/mirrors/sharp/"
npm_config_sharp_libvips_binary_host="https://npmmirror.com/mirrors/sharp-libvips"
npm_config_profiler_binary_host_mirror="https://npmmirror.com/mirrors/node-inspector/"
npm_config_fse_binary_host_mirror="https://npmmirror.com/mirrors/fsevents"
npm_config_node_sqlite3_binary_host_mirror="https://npmmirror.com/mirrors"
npm_config_sqlite3_binary_host_mirror="https://npmmirror.com/mirrors"
npm_config_sqlite3_binary_site="https://npmmirror.com/mirrors/sqlite3"
npm_config_electron_mirror="https://npmmirror.com/mirrors/electron/v"
PUPPETEER_DOWNLOAD_BASE_URL="https://npmmirror.com/mirrors"
npm_config_chromedriver_cdnurl="https://npmmirror.com/mirrors/chromedriver"
npm_config_operadriver_cdnurl="https://npmmirror.com/mirrors/operadriver"
npm_config_phantomjs_cdnurl="https://npmmirror.com/mirrors/phantomjs"
npm_config_python_mirror="https://npmmirror.com/mirrors/python"
npm_config_sass_binary_site="https://npmmirror.com/mirrors/node-sass"

[test]
# `preload` 字段告诉 bun test 在运行测试文件之前要加载的脚本
# Bun 会自动执行这个文件，从而设置好全局 DOM 环境
preload = ["./tests/setup.tsx"]

# 如果你的 React 组件使用了 JSX，确保 `jsx` 配置正确
[jsx]
# "react-jsx" 是现代 React 的标准
transform = "react-jsx"


